version: '2'
services:
  samplereactcouchbasecaffeine-app:
    image: samplereactcouchbasecaffeine
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=samplereactcouchbasecaffeine-couchbase
      - SPRING_COUCHBASE_BUCKET_NAME=sampleReactCouchbaseCaffeine
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  samplereactcouchbasecaffeine-couchbase:
    extends:
      file: couchbase.yml
      service: samplereactcouchbasecaffeine-couchbase
