version: '2'
services:
  samplereactcouchbasecaffeine-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    environment:
      - TYPE=MASTER
      - BUCKET=sampleReactCouchbaseCaffeine
  samplereactcouchbasecaffeine-couchbase-node:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    environment:
      - TYPE=WORKER
      - BUCKET=sampleReactCouchbaseCaffeine
      - COUCHBASE_MASTER=samplereactcouchbasecaffeine-couchbase
      - AUTO_REBALANCE=false
